config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users
  root 'hellos#index'
  resources :hellos do
  	collection do
  		get :my_links
  	end
  end
  resources :tags
  end

app/models/hello.rb
class Hello
  include Mongoid::Document
  field :url, type: String
  field :summary, type: String

  before_destroy :delete_tags

  has_and_belongs_to_many :tags
  belongs_to :user

  validates_presence_of :url, :summary

  def all_tags
		self.tags.map(&:name).join(', ')
	end

	def all_tags=(names)
		self.tags = names.split(',').map do |name|
			Tag.where(name: name.strip).first_or_create!
		end
	end

  private

  def delete_tags
    self.tags.each{ |tag| tag.delete if tag.hellos.count == 1 }
  end

end

app/models/tag.rb
class Tag
  include Mongoid::Document
  field :name, type: String

  has_and_belongs_to_many :hellos 
	
end

app/models/user.rb
class User
  include Mongoid::Document
  extend Devise::Models
  has_many :hellos
  field :admin, type: Boolean
  #validates_presence_of :name
  #validates_uniqueness_of :email, :case_sensitive => false
  #attr_accessor :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  # field :sign_in_count,      type: Integer, default: 0
  # field :current_sign_in_at, type: Time
  # field :last_sign_in_at,    type: Time
  # field :current_sign_in_ip, type: String
  # field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	add_flash_types :success, :danger
end

app/controllers/hellos_controller.rb
class HellosController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_hello, only: [:show, :edit, :update, :destroy]
  before_action :require_permission, only: :edit

  def index
    @hellos = Hello.all
  end

  def show
    respond_to do |format|
       format.html
       format.pdf do
         render pdf: "filename"
       end
      end
  end

  def new
    @hello = Hello.new
    @hello.user = current_user
  end

  def create
    @hello = Hello.new(hello_params)
    @hello.user = current_user
    if @hello.save
      redirect_to @hello, success: 'Hello successfully created'
    else
      render :new, danger: 'Hello don`t created'
    end
  end

  def edit
  end

  def update
    if @hello.update_attributes(hello_params)
      redirect_to @hello, success: 'Hello successfully updated'
    else
      render :edit, danger: 'Hello don`t updated'
    end
  end

  def destroy
    @hello.destroy
    @tags = @hello.tags
    if @tags
      redirect_to hellos_path, success: 'Hello successfully deleted'
    end
  end

  def my_links
    @links = Hello.where(user_id: current_user.id)
    @my_tags = []
    @links.each do |hello|
      hello.tags.each{ |tag| @my_tags << tag }
    end
    @my_tags.uniq!
  end

  private

  def set_hello
    @hello = Hello.find(params[:id])
  end

  def hello_params
    params.require(:hello).permit(:url, :summary, :all_tags)
  end

  def require_permission
    if current_user != Hello.find(params[:id]).user
      redirect_to root_path
    end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	def index
		@tags = Tag.all					
	end

	def show
		@tag = Tag.find_by(name: params[:id])
		@hellos = @tag.hellos
	end	

	def destroy
		@tag = Tag.find(params[:id])
		@tag.destroy 
		redirect_to tags_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for(name)
		{
			success: "alert-succes",
			error: "alert-danger",
			denger: "alert-danger",
			alert: "alert-warning",
			notice: "alert-info"
		}[name.to_sym] || name
	end
end

app/helpers/hellos_helper.rb
module HellosHelper
end

app/helpers/url_helper.rb
module UrlHelper
	def to_url(url)
		/^http/i.match(url) ? url : "http://#{url}"
	end
end

app/views/hellos/_all_tags.html.erb
<% Tag.all.each do |tag| %>
 <li>
  <ul>
  	<%= link_to "##{tag.name}", tag_path(tag.name) %>
 	</ul>
<% end %> 

app/views/hellos/_form.html.erb
<% if @hello.errors.any? %>
	<div class="alert alert-danger">
		<h5><%= t('common.errors') %></h5>
		<ul>
			<% @hello.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>			
		</ul>
	</div>
<% end %>

<%= form_for @hello do |f| %>

	<div class="form-group">
		<%= f.label :summary %>
		<%= f.text_area :summary, class: 'form-control' %>		
	</div>

	<div class="form-group">
		<%= f.label :url %>
		<%= f.text_field :url, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :all_tags %>
		<%= f.text_field :all_tags, class: 'form-control' %>		
	</div>

	<div class="form-group">
	  <%= f.submit 'Save Link', class: 'btn btn-primary' %>
	  <%= link_to 'Back', :back, class: 'btn btn-outline-secondary' %>
  </div>

<% end %>

app/views/hellos/_hello.html.erb
<article class="link">

	<section class="link-head">
		<small>
			<%= hello.user.email %>
			<% if hello.user == current_user %>			
				|					
				<%= link_to 'Edit', edit_hello_path(hello) %>
				|
				<%= link_to 'Delete', hello_path(hello), method: :delete, data: { confirm: 'Are you chure ?' } %>
			<% end %>
		</small>
	</section>

	<section class="link-body">
		<p><%= link_to hello.summary, hello_path(hello) %></p>
		<h3><code><%= link_to hello.url, to_url(hello.url), target: "_blank" %></code></h3>
	</section>
		
	<section class="footer-summary">
		<%= raw hello.tags.map{ |tag| link_to "##{tag.name}", tag_path(tag.name), class: 'badge badge-primary' }.join(' ') %>
	</section>
</article>

app/views/hellos/edit.html.erb
<h2>Edit Link</h2>

<%= render 'form' %>

app/views/hellos/index.html.erb
<h1>All Links:</h1>

<%= render @hellos %>

app/views/hellos/my_links.html.erb
<div class="row">
  <div class="col-md-10">
    <h2>My Links:</h2>

    <%= render @links %>
  </div>
  <div class="col-md-2">
    <h3>My Tags:</h3>

    <% @my_tags.each do |tag| %>
      <ul>
        <li>
          <%= link_to "##{tag.name}", tag_path(tag.name) %>
        </li>
      </ul>
    <% end %>       
  </div>
</div>

app/views/hellos/new.html.erb
<h2>New Link</h2>

<%= render 'form' %>

app/views/hellos/show.html.erb
<h1>Link</h1>

<%= render @hello %>

<%= link_to 'Create PDF document', hello_path(@hello, :format => :pdf) %>

app/views/hellos/show.pdf.erb
  <h1><%= @hello.url %></h1>
  <p><%= @hello.summary %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MongoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'partials/navbar' %>

    <div class="container main">      
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |name, message| %>
            <div class="alert alert-<%= name %>">
              <button class="close" data-dismiss="alert">&times;</button>
              <%= message %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-10">
          <%= yield %>
        </div>
        <div class="col-md-2">
          <% if user_signed_in? %>
            <h2>All Tags:</h2> 
            <%= render "/hellos/all_tags" %>
          <% end %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/partials/_navbar.html.erb
<div class="container navbar-all">
  <nav class="navbar navbar-expand-lg">
    <a class="navbar-brand" href="<%= hellos_path %>">Linker</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav pull-xs-right">
        <% if user_signed_in? %>          
          <li class="nav-item">
            <li><%= link_to 'My Links', my_links_hellos_path,  class: "nav-link" %></li>
          </li>
          <li class="nav-item">
            <%= link_to "New Link", new_hello_path, class: "btn btn-outline-primary pull-xs-right" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <li class="nav-link"><%= current_user.email %></li>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path,  class: "nav-link" %>
          </li>          
        <% end %>
      </ul>      
    </div>
  </nav>
</div>

app/views/tags/index.html.erb
<% (Tag.all).each do |tag| %>
 <li>
  <ul>
  	<%= link_to "##{tag.name}", tag_path(tag) %>
  		<small>
  			<%= link_to 'Delete', tag_path(tag), method: :delete %>
  		</small>
 	</ul>
<% end %> 

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>

<% if @tag.hellos.empty? %>
<%= @hellos.destroy %>
	<h2>Tag is missing</h2>
<% else %>
	<%= render @tag.hellos %>
<% end %>